import { MD3LightTheme, type MD3Theme } from 'react-native-paper';
import { colors } from '@/src/theme/tokens';

export const paperTheme: MD3Theme = {
  ...MD3LightTheme,
  roundness: 3,
  colors: {
    ...MD3LightTheme.colors,
    primary: colors.primary,
    onPrimary: colors.white,
    primaryContainer: '#C8E6C9',
    onPrimaryContainer: colors.primaryPressed,
    secondary: colors.accent,
    onSecondary: colors.white,
    secondaryContainer: '#F8D4B8',
    onSecondaryContainer: '#5C2A10',
    tertiary: colors.success,
    onTertiary: colors.white,
    tertiaryContainer: '#D8F3DC',
    onTertiaryContainer: '#0F3D24',
    error: colors.danger,
    onError: colors.white,
    errorContainer: '#F9D2CF',
    onErrorContainer: '#5C120C',
    background: colors.background,
    onBackground: colors.text,
    surface: colors.surface,
    onSurface: colors.text,
    surfaceVariant: colors.surfaceMuted,
    onSurfaceVariant: colors.textMuted,
    surfaceDisabled: 'rgba(26, 33, 28, 0.12)',
    onSurfaceDisabled: 'rgba(26, 33, 28, 0.38)',
    outline: colors.border,
    outlineVariant: colors.border,
    inverseSurface: colors.text,
    inverseOnSurface: colors.surface,
    inversePrimary: '#8FCBBA',
    backdrop: 'rgba(26, 33, 28, 0.4)',
    elevation: {
      ...MD3LightTheme.colors.elevation,
      level0: 'transparent',
      level1: '#F6FBF7',
      level2: '#F0F8F2',
      level3: '#EAF4EC',
      level4: '#E6F2E8',
      level5: '#E2F0E5',
    },
  },
};
