import { MD3LightTheme, type MD3Theme } from 'react-native-paper';
import { colors } from '@/src/theme/tokens';

export const paperTheme: MD3Theme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: colors.primary,
    onPrimary: colors.white,
    primaryContainer: '#C5DED6',
    onPrimaryContainer: colors.primaryPressed,
    secondary: colors.accent,
    onSecondary: colors.white,
    secondaryContainer: '#F3D8C8',
    onSecondaryContainer: '#5C2A10',
    tertiary: colors.success,
    onTertiary: colors.white,
    tertiaryContainer: '#C8E6D4',
    onTertiaryContainer: '#0F3D24',
    error: colors.danger,
    onError: colors.white,
    errorContainer: '#F9D2CF',
    onErrorContainer: '#5C120C',
    background: colors.background,
    onBackground: colors.text,
    surface: colors.surface,
    onSurface: colors.text,
    surfaceVariant: colors.surfaceMuted,
    onSurfaceVariant: colors.textMuted,
    surfaceDisabled: 'rgba(28, 25, 20, 0.12)',
    onSurfaceDisabled: 'rgba(28, 25, 20, 0.38)',
    outline: colors.border,
    outlineVariant: colors.border,
    inverseSurface: colors.text,
    inverseOnSurface: colors.surface,
    inversePrimary: '#8FCBBA',
    backdrop: 'rgba(28, 25, 20, 0.4)',
    elevation: {
      ...MD3LightTheme.colors.elevation,
      level0: 'transparent',
      level1: colors.surface,
      level2: colors.surface,
      level3: colors.surface,
      level4: colors.surface,
      level5: colors.surface,
    },
  },
};
